/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package launcheruniversae;

import java.awt.Dimension;

/**
 *
 * @author joseg
 */
public class PanelCarrusel extends javax.swing.JPanel {

    private String[] imagenes = {
        "src/imagenes/Embarque0.png",
        "src/imagenes/Embarque1.png",
        "src/imagenes/Embarque0.png"
    };

    private int imagenActual = 0; //Índice de la imagen actual
    public PanelCarrusel() {
        initComponents();
        Utilidades.SetImageLabelDimension(jLabel3, "src/imagenes/Barrita aislada descripción.png", new Dimension(jLabel3.getWidth(), jLabel3.getHeight()), true);

    }

    public void volverAlHome() {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof Launcher) {
            Launcher launcher = (Launcher) window;
            PanelHome panelHome = new PanelHome();
            Utilidades.PanelInPanel(launcher.getContentPanel(), panelHome);
        }
    }

    private void actualizarImagen() {
        Utilidades.SetImageLabelDimension(imageLabel, imagenes[imagenActual],
                new Dimension(imageLabel.getWidth(), imageLabel.getHeight()), true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageLabel2 = new javax.swing.JLabel();
        imageLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1340, 710));
        setMinimumSize(new java.awt.Dimension(1340, 710));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1340, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Embarque y desembarque en helicóptero");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Embarque0.png"))); // NOI18N
        imageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 880));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flecha izquierda.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flecha derecha.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 220, -1, -1));

        imageLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuadrado fondo enfocado.png"))); // NOI18N
        imageLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(imageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 1550, 880));

        imageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imageLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cuadrado fondo enfocado.png"))); // NOI18N
        imageLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(imageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 740, 880));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 20, 40));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Embarque y desembarque en helicóptero");
        jTextField1.setBorder(null);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JLabel imageLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
