/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Objetos.*;
import Utilidades.EstilosUtil;

/**
 *
 * @author joseg
 */
public class VentanaHongos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnimales
     */
    
private DefaultTableModel modelo;
private ArrayList<Hongos> listaHongos;

public VentanaHongos() {
    initComponents();
    ComboTipoHongo.addActionListener(e -> actualizarEtiquetaCaracteristica());
    inicializarTabla();
    cargarDatosEjemplo();
    limpiarCampos();
}

private void inicializarTabla() {
    modelo = new DefaultTableModel(
        new Object[][] {},
        new String[] {"Tipo", "Nombre", "Edad", "Color", "Especie", "Característica"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    jTable1.setModel(modelo);
   // Aplicar estilos a la tabla
    jTable1.setModel(modelo);
    EstilosUtil.aplicarEstiloTabla(jTable1);

}
private void actualizarEtiquetaCaracteristica() {
    String tipoSeleccionado = (String) ComboTipoHongo.getSelectedItem();
                txtCaracteristicaHongo.setVisible(false);

    //Removemos el campo actual antes de cambiarlo

    
    switch (tipoSeleccionado) {
        case "Seta":
            jLabel8.setText("Tipo de Esporas");
            txtCaracteristicaHongo.setVisible(true);
            jCheckBox1.setVisible(false);

            break;
        case "Moho":
            jLabel8.setText("Superficie");
            txtCaracteristicaHongo.setVisible(true);
            jCheckBox1.setVisible(false);

            break;
        case "Levadura":
            jLabel8.setText("Uso Alimentario");
            txtCaracteristicaHongo.setVisible(false);
            jCheckBox1.setVisible(true);
            break;
        default:
            jLabel8.setText("Característica");
            txtCaracteristicaHongo.setVisible(true);
            jCheckBox1.setVisible(false);


    }
    
    txtCaracteristicaHongo.setText(""); // Limpiar el campo cuando cambia la selección
}

private void cargarDatosEjemplo() {
    listaHongos = Hongos.cargarHongosEjemplo();
    
    for (Hongos hongo : listaHongos) {
        String tipo = hongo.getClass().getSimpleName();
        String caracteristica = "";
        String color = "";
        
        if (hongo instanceof Seta) {
            color = ((Seta) hongo).getColor();
            caracteristica = "Tipo esporas: " + hongo.getTipoEsporas();
        } else if (hongo instanceof Moho) {
            caracteristica = "Superficie: " + ((Moho) hongo).getSuperficiePreferida();
        } else if (hongo instanceof Levadura) {
            caracteristica = "Uso alimentario: " + (((Levadura) hongo).isSeUsaEnAlimentos() ? "Sí" : "No");
        }
        

        
        modelo.addRow(new Object[] {
            tipo,
            hongo.getNombre(),
            hongo.getEdad(),
            color,
            hongo.getModoReproduccion(),
            caracteristica
        });
    }
}
private void limpiarCampos() {
    ComboTipoHongo.setSelectedIndex(0);
    txtNombre.setText("");
    txtEdad.setText("");
    txtColor.setText("");
    txtTamaño.setText("");
    txtEspecieHongo.setText("");
    txtCaracteristicaHongo.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ComboTipoHongo = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtTamaño = new javax.swing.JTextField();
        txtEspecieHongo = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtCaracteristicaHongo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Animales");

        jPanel1.setBackground(new java.awt.Color(245, 245, 247));

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN DE HONGOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setBackground(new java.awt.Color(245, 245, 247));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jTable1.setFont(new java.awt.Font("Sans Serif Collection", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre", "Edad", "Color", "Tamaño", "Especie", "Característica"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(5);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(245, 245, 247));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Hongo:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel4.setText("Edad:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel5.setText("Color:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel6.setText("Tamaño:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel7.setText("Especie:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel8.setText("Característica:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 336, -1, -1));

        ComboTipoHongo.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        ComboTipoHongo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar:", "Seta", "Moho", "Levadura" }));
        ComboTipoHongo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(ComboTipoHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 6, -1, -1));

        txtNombre.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 64, 168, -1));

        txtEdad.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtEdad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 118, 168, -1));

        txtColor.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtColor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 172, 168, -1));

        txtTamaño.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtTamaño.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 226, 168, -1));

        txtEspecieHongo.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtEspecieHongo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtEspecieHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 280, 168, -1));
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 344, -1, -1));

        txtCaracteristicaHongo.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        txtCaracteristicaHongo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel3.add(txtCaracteristicaHongo, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 334, 170, -1));

        jButton1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 483, -1, -1));

        jButton2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 483, -1, -1));

        jButton3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jButton3.setText("EDITAR");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 483, 73, -1));

        jSplitPane1.setLeftComponent(jPanel3);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
        // Validar que no haya campos vacíos
        if (ComboTipoHongo.getSelectedIndex() == 0 || 
            txtNombre.getText().trim().isEmpty() ||
            txtEdad.getText().trim().isEmpty() ||
            txtColor.getText().trim().isEmpty() ||
            txtTamaño.getText().trim().isEmpty() ||
            txtEspecieHongo.getText().trim().isEmpty() ||
            txtCaracteristicaHongo.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Por favor, complete todos los campos", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Agregar datos a la tabla
        modelo.addRow(new Object[] {
            ComboTipoHongo.getSelectedItem(),
            txtNombre.getText(),
            txtEdad.getText(),
            txtColor.getText(),
            txtTamaño.getText(),
            txtEspecieHongo.getText(),
            txtCaracteristicaHongo.getText()
        });
        
        // Limpiar campos después de agregar
        limpiarCampos();
        
        JOptionPane.showMessageDialog(this, 
            "Hongo agregado correctamente", 
            "Éxito", 
            JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al agregar Hongo: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un Hongo para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    modelo.removeRow(filaSeleccionada);
    listaHongos.remove(filaSeleccionada);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un Hongo para editar", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    ComboTipoHongo.setSelectedItem(modelo.getValueAt(filaSeleccionada, 0));
    txtNombre.setText(modelo.getValueAt(filaSeleccionada, 1).toString());
    txtEdad.setText(modelo.getValueAt(filaSeleccionada, 2).toString());
    txtColor.setText(modelo.getValueAt(filaSeleccionada, 3).toString());
    txtTamaño.setText(modelo.getValueAt(filaSeleccionada, 4).toString());
    txtEspecieHongo.setText(modelo.getValueAt(filaSeleccionada, 5).toString());
    txtCaracteristicaHongo.setText(modelo.getValueAt(filaSeleccionada, 6).toString());

    modelo.removeRow(filaSeleccionada);
    listaHongos.remove(filaSeleccionada);


                                       
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHongos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHongos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHongos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHongos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHongos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboTipoHongo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCaracteristicaHongo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecieHongo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
